import { LEAGUES } from "../leagues";
import { predict } from "../model";
import type {
  Highlight,
  LineupPlayer,
  Match,
  MatchDetail,
  OddsQuote,
  StandingRow,
  Team,
} from "../types";

const crest = (id: number) => `https://media.api-sports.io/football/teams/${id}.png`;

function t(id: string, name: string, short: string, n: number): Team {
  return { id, name, short, crest: crest(n) };
}

export const TEAMS = {
  villa: t("villa", "Aston Villa", "AVL", 66),
  arsenal: t("arsenal", "Arsenal", "ARS", 42),
  city: t("city", "Manchester City", "MCI", 50),
  liverpool: t("liverpool", "Liverpool", "LIV", 40),
  chelsea: t("chelsea", "Chelsea", "CHE", 49),
  united: t("united", "Manchester United", "MUN", 33),
  spurs: t("spurs", "Tottenham Hotspur", "TOT", 47),
  newcastle: t("newcastle", "Newcastle United", "NEW", 34),
  brighton: t("brighton", "Brighton", "BHA", 51),
  everton: t("everton", "Everton", "EVE", 45),
  forest: t("forest", "Nottingham Forest", "NFO", 65),
  brentford: t("brentford", "Brentford", "BRE", 55),
  fulham: t("fulham", "Fulham", "FUL", 36),
  palace: t("palace", "Crystal Palace", "CRY", 52),
  bournemouth: t("bournemouth", "Bournemouth", "BOU", 35),
  leeds: t("leeds", "Leeds United", "LEE", 63),
  hull: t("hull", "Hull City", "HUL", 64),
  sunderland: t("sunderland", "Sunderland", "SUN", 746),
  ipswich: t("ipswich", "Ipswich Town", "IPS", 57),
  coventry: t("coventry", "Coventry City", "COV", 71),
  barca: t("barca", "Barcelona", "BAR", 529),
  rayo: t("rayo", "Rayo Vallecano", "RAY", 728),
  osasuna: t("osasuna", "Osasuna", "OSA", 727),
  getafe: t("getafe", "Getafe", "GET", 546),
  madrid: t("madrid", "Real Madrid", "RMA", 541),
  betis: t("betis", "Real Betis", "BET", 543),
  roma: t("roma", "Roma", "ROM", 497),
  lecce: t("lecce", "Lecce", "LEC", 867),
  atalanta: t("atalanta", "Atalanta", "ATA", 499),
  bologna: t("bologna", "Bologna", "BOL", 500),
  benfica: t("benfica", "Benfica", "BEN", 211),
  estoril: t("estoril", "Estoril", "EST", 230),
  braga: t("braga", "Braga", "BRA", 218),
  guima: t("guima", "Vitória Guimarães", "VGU", 224),
  psg: t("psg", "Paris Saint-Germain", "PSG", 85),
  monaco: t("monaco", "AS Monaco", "ASM", 91),
  lille: t("lille", "Lille", "LIL", 79),
  lyon: t("lyon", "Lyon", "OL", 80),
  om: t("om", "Marseille", "OM", 81),
  rennes: t("rennes", "Rennes", "REN", 94),
  lens: t("lens", "Lens", "RCL", 116),
  pfc: t("pfc", "Paris FC", "PFC", 111),
  troyes: t("troyes", "Troyes", "EST", 110),
  strasbourg: t("strasbourg", "Strasbourg", "RCS", 95),
  brest: t("brest", "Brest", "SB29", 106),
  angers: t("angers", "Angers", "SCO", 77),
  lorient: t("lorient", "Lorient", "FCL", 266),
  hac: t("hac", "Le Havre", "HAC", 111),
  toulouse: t("toulouse", "Toulouse", "TFC", 96),
  nice: t("nice", "Nice", "OGCN", 84),
  auxerre: t("auxerre", "Auxerre", "AJA", 130),
  lemans: t("lemans", "Le Mans", "MUC", 1304),
};

function books(
  home: number,
  draw: number,
  away: number,
  extras: Partial<OddsQuote> = {},
): OddsQuote[] {
  const jitter = (n: number, j: number) => +(n * j).toFixed(2);
  return [
    { bookmaker: "Winamax", home, draw, away, ...extras },
    {
      bookmaker: "Betclic",
      home: jitter(home, 0.98),
      draw: jitter(draw, 1.03),
      away: jitter(away, 1.02),
      ...extras,
    },
    {
      bookmaker: "Unibet",
      home: jitter(home, 1.02),
      draw: jitter(draw, 0.97),
      away: jitter(away, 0.99),
      ...extras,
    },
    {
      bookmaker: "Pinnacle",
      home: jitter(home, 1.04),
      draw: jitter(draw, 1.01),
      away: jitter(away, 1.03),
      ...extras,
    },
    {
      bookmaker: "Bet365",
      home: jitter(home, 0.99),
      draw: jitter(draw, 1.0),
      away: jitter(away, 1.01),
      ...extras,
    },
  ];
}

function match(partial: Omit<Match, "prediction" | "sources" | "status" | "minute" | "score"> & {
  status?: Match["status"];
  minute?: number | null;
  score?: Match["score"];
}): Match {
  const prediction = predict(partial.home.name, partial.away.name);
  return {
    status: partial.status ?? "scheduled",
    minute: partial.minute ?? null,
    score: partial.score ?? { home: null, away: null },
    sources: ["fallback", "model"],
    prediction,
    ...partial,
  };
}

/** Kickoffs stored in UTC. 31 Aug 2026 evening (Europe). */
export const MATCHES: Match[] = [
  match({
    id: "lecce-roma",
    kickoff: "2026-08-31T16:30:00Z",
    league: LEAGUES.seriea,
    home: TEAMS.lecce,
    away: TEAMS.roma,
    venue: "Via del Mare, Lecce",
    referee: "M. Guida",
    events: [
      { minute: 9, type: "yellow", team: "home", player: "Berisha" },
      { minute: 18, type: "goal", team: "away", player: "Dovbyk", assist: "Dybala" },
      { minute: 33, type: "yellow", team: "away", player: "Cristante" },
      { minute: 41, type: "goal", team: "home", player: "Krstovic", assist: "Pierotti" },
      { minute: 58, type: "sub", team: "away", player: "Pellegrini" },
      { minute: 67, type: "goal", team: "away", player: "Dybala" },
      { minute: 79, type: "yellow", team: "home", player: "Ramadani" },
      { minute: 88, type: "goal", team: "away", player: "Soulé" },
    ],
    odds: books(4.8, 3.55, 1.78, { over25: 2.05, under25: 1.78, bttsYes: 1.87, bttsNo: 1.92 }),
    highlightThumb: "/hero-camp-nou.jpg",
  }),
  match({
    id: "osasuna-getafe",
    kickoff: "2026-08-31T17:30:00Z",
    league: LEAGUES.laliga,
    home: TEAMS.osasuna,
    away: TEAMS.getafe,
    venue: "El Sadar, Pampelune",
    referee: "J. Martínez",
    events: [
      { minute: 14, type: "yellow", team: "away", player: "Milla" },
      { minute: 27, type: "goal", team: "home", player: "Budimir", assist: "Barja" },
      { minute: 52, type: "yellow", team: "home", player: "Torró" },
      { minute: 71, type: "goal", team: "away", player: "Mayoral" },
      { minute: 84, type: "red", team: "away", player: "Alderete" },
    ],
    odds: books(2.35, 3.05, 3.4, { over25: 2.4, under25: 1.55, bttsYes: 2.05, bttsNo: 1.75 }),
  }),
  match({
    id: "atalanta-bologna",
    kickoff: "2026-08-31T18:45:00Z",
    league: LEAGUES.seriea,
    home: TEAMS.atalanta,
    away: TEAMS.bologna,
    venue: "Gewiss Stadium, Bergame",
    referee: "D. Doveri",
    events: [
      { minute: 7, type: "goal", team: "home", player: "Lookman", assist: "De Ketelaere" },
      { minute: 22, type: "goal", team: "home", player: "Retegui" },
      { minute: 39, type: "yellow", team: "away", player: "Ferguson" },
      { minute: 63, type: "goal", team: "away", player: "Castro", assist: "Orsolini" },
      { minute: 81, type: "goal", team: "home", player: "De Ketelaere" },
    ],
    odds: books(1.72, 3.8, 4.7, { over25: 1.82, under25: 2.0, bttsYes: 1.74, bttsNo: 2.08 }),
  }),
  match({
    id: "villa-arsenal",
    kickoff: "2026-08-31T19:00:00Z",
    league: LEAGUES.pl,
    home: TEAMS.villa,
    away: TEAMS.arsenal,
    venue: "Villa Park, Birmingham",
    referee: "A. Taylor",
    highlightThumb: "/hero-villa.jpg",
    events: [
      { minute: 12, type: "yellow", team: "home", player: "Kamara" },
      { minute: 24, type: "goal", team: "away", player: "Saka", assist: "Ødegaard" },
      { minute: 38, type: "yellow", team: "away", player: "Rice" },
      { minute: 51, type: "goal", team: "home", player: "Watkins", assist: "Rogers" },
      { minute: 66, type: "goal", team: "away", player: "Gyökeres", assist: "Saka" },
      { minute: 74, type: "sub", team: "home", player: "Bailey" },
      { minute: 89, type: "yellow", team: "home", player: "Konsa" },
    ],
    odds: books(4.9, 3.85, 1.7, { over25: 1.85, under25: 1.97, bttsYes: 1.8, bttsNo: 2.0 }),
  }),
  match({
    id: "benfica-estoril",
    kickoff: "2026-08-31T19:15:00Z",
    league: LEAGUES.liga,
    home: TEAMS.benfica,
    away: TEAMS.estoril,
    venue: "Estádio da Luz, Lisbonne",
    events: [
      { minute: 11, type: "goal", team: "home", player: "Pavlidis", assist: "Di María" },
      { minute: 34, type: "goal", team: "home", player: "Aktürkoğlu" },
      { minute: 70, type: "goal", team: "home", player: "Pavlidis" },
    ],
    odds: books(1.22, 6.4, 12, { over25: 1.55, under25: 2.4 }),
  }),
  match({
    id: "braga-guima",
    kickoff: "2026-08-31T19:15:00Z",
    league: LEAGUES.liga,
    home: TEAMS.braga,
    away: TEAMS.guima,
    venue: "Estádio Municipal, Braga",
    events: [
      { minute: 29, type: "goal", team: "home", player: "El Ouazzani" },
      { minute: 77, type: "goal", team: "away", player: "Händel" },
    ],
    odds: books(1.85, 3.45, 4.3),
  }),
  match({
    id: "barca-rayo",
    kickoff: "2026-08-31T19:30:00Z",
    league: LEAGUES.laliga,
    home: TEAMS.barca,
    away: TEAMS.rayo,
    venue: "Spotify Camp Nou, Barcelone",
    referee: "C. Soto Grado",
    highlightThumb: "/hero-camp-nou.jpg",
    events: [
      { minute: 8, type: "goal", team: "home", player: "Yamal", assist: "Pedri" },
      { minute: 19, type: "goal", team: "home", player: "Lewandowski", assist: "Raphinha" },
      { minute: 44, type: "yellow", team: "away", player: "Ciss" },
      { minute: 61, type: "goal", team: "home", player: "Raphinha" },
      { minute: 83, type: "goal", team: "away", player: "De Frutos" },
    ],
    odds: books(1.22, 6.6, 13.5, { over25: 1.48, under25: 2.62, bttsYes: 2.15, bttsNo: 1.68 }),
  }),
  match({
    id: "manu-ipswich",
    kickoff: "2026-08-30T15:00:00Z",
    league: LEAGUES.pl,
    home: TEAMS.united,
    away: TEAMS.ipswich,
    venue: "Old Trafford",
    events: [
      { minute: 7, type: "goal", team: "home", player: "Cunha" },
      { minute: 18, type: "goal", team: "home", player: "Mbeumo" },
      { minute: 29, type: "goal", team: "away", player: "Delap" },
      { minute: 41, type: "goal", team: "home", player: "Bruno Fernandes", assist: "Amad" },
      { minute: 67, type: "goal", team: "home", player: "Amad" },
      { minute: 81, type: "goal", team: "away", player: "Hutchinson" },
      { minute: 88, type: "goal", team: "home", player: "Zirkzee" },
    ],
    odds: books(1.45, 4.6, 6.4),
  }),
  match({
    id: "chelsea-brighton",
    kickoff: "2026-08-30T14:00:00Z",
    league: LEAGUES.pl,
    home: TEAMS.chelsea,
    away: TEAMS.brighton,
    venue: "Stamford Bridge",
    events: [
      { minute: 6, type: "goal", team: "home", player: "Palmer" },
      { minute: 21, type: "goal", team: "away", player: "Mitoma" },
      { minute: 33, type: "goal", team: "home", player: "Jackson" },
      { minute: 48, type: "goal", team: "away", player: "Pedro" },
      { minute: 62, type: "goal", team: "home", player: "Palmer" },
      { minute: 74, type: "goal", team: "away", player: "Minteh" },
      { minute: 90, type: "goal", team: "home", player: "Caicedo" },
    ],
    odds: books(1.95, 3.7, 3.75),
  }),
  match({
    id: "leeds-brentford",
    kickoff: "2026-08-30T14:00:00Z",
    league: LEAGUES.pl,
    home: TEAMS.leeds,
    away: TEAMS.brentford,
    events: [
      { minute: 40, type: "goal", team: "home", player: "Aaronson" },
      { minute: 78, type: "goal", team: "away", player: "Wissa" },
    ],
    odds: books(2.4, 3.3, 2.95),
  }),
  match({
    id: "sunderland-fulham",
    kickoff: "2026-08-30T14:00:00Z",
    league: LEAGUES.pl,
    home: TEAMS.sunderland,
    away: TEAMS.fulham,
    events: [{ minute: 57, type: "goal", team: "home", player: "Isidor" }],
    odds: books(2.7, 3.2, 2.7),
  }),
  match({
    id: "liverpool-forest",
    kickoff: "2026-08-29T12:30:00Z",
    league: LEAGUES.pl,
    home: TEAMS.liverpool,
    away: TEAMS.forest,
    venue: "Anfield",
    events: [
      { minute: 16, type: "goal", team: "home", player: "Salah" },
      { minute: 28, type: "goal", team: "away", player: "Wood" },
      { minute: 55, type: "goal", team: "home", player: "Szoboszlai" },
      { minute: 82, type: "goal", team: "away", player: "Gibbs-White" },
    ],
    odds: books(1.4, 4.8, 7.5),
  }),
  match({
    id: "bournemouth-everton",
    kickoff: "2026-08-29T14:00:00Z",
    league: LEAGUES.pl,
    home: TEAMS.bournemouth,
    away: TEAMS.everton,
    events: [
      { minute: 23, type: "goal", team: "home", player: "Kluivert" },
      { minute: 61, type: "goal", team: "away", player: "Beto" },
    ],
    odds: books(2.15, 3.4, 3.4),
  }),
  match({
    id: "coventry-hull",
    kickoff: "2026-08-29T14:00:00Z",
    league: LEAGUES.pl,
    home: TEAMS.coventry,
    away: TEAMS.hull,
    events: [{ minute: 74, type: "goal", team: "away", player: "João Pedro" }],
    odds: books(2.5, 3.2, 2.9),
  }),
  match({
    id: "spurs-newcastle",
    kickoff: "2026-08-29T16:30:00Z",
    league: LEAGUES.pl,
    home: TEAMS.spurs,
    away: TEAMS.newcastle,
    venue: "Tottenham Hotspur Stadium",
    events: [
      { minute: 31, type: "goal", team: "away", player: "Isak" },
      { minute: 69, type: "goal", team: "away", player: "Gordon" },
    ],
    odds: books(2.45, 3.45, 2.8),
  }),
  match({
    id: "monaco-auxerre",
    kickoff: "2026-08-30T18:45:00Z",
    league: LEAGUES.ligue1,
    home: TEAMS.monaco,
    away: TEAMS.auxerre,
    venue: "Louis-II",
    events: [
      { minute: 19, type: "goal", team: "home", player: "Biereth" },
      { minute: 64, type: "goal", team: "home", player: "Minamino" },
    ],
    odds: books(1.4, 4.6, 7.2),
  }),
  match({
    id: "psg-brest",
    kickoff: "2026-08-30T19:45:00Z",
    league: LEAGUES.ligue1,
    home: TEAMS.psg,
    away: TEAMS.brest,
    venue: "Parc des Princes",
    events: [
      { minute: 34, type: "goal", team: "home", player: "Dembélé" },
      { minute: 71, type: "goal", team: "away", player: "Del Castillo" },
    ],
    odds: books(1.18, 7.2, 14),
  }),
  match({
    id: "pfc-nice",
    kickoff: "2026-08-30T15:00:00Z",
    league: LEAGUES.ligue1,
    home: TEAMS.pfc,
    away: TEAMS.nice,
    venue: "Stade Charléty",
    events: [
      { minute: 12, type: "goal", team: "home", player: "Krasso" },
      { minute: 40, type: "goal", team: "home", player: "Gory" },
      { minute: 88, type: "goal", team: "home", player: "Dembélé" },
    ],
    odds: books(3.1, 3.2, 2.35),
  }),
  match({
    id: "om-strasbourg",
    kickoff: "2026-08-29T19:00:00Z",
    league: LEAGUES.ligue1,
    home: TEAMS.om,
    away: TEAMS.strasbourg,
    venue: "Vélodrome",
    events: [
      { minute: 9, type: "goal", team: "home", player: "Greenwood" },
      { minute: 55, type: "goal", team: "home", player: "Gouiri" },
      { minute: 80, type: "goal", team: "away", player: "Emegha" },
    ],
    odds: books(1.7, 3.85, 4.8),
  }),
  match({
    id: "lille-lyon",
    kickoff: "2026-08-30T17:00:00Z",
    league: LEAGUES.ligue1,
    home: TEAMS.lille,
    away: TEAMS.lyon,
    events: [
      { minute: 27, type: "goal", team: "home", player: "David" },
      { minute: 49, type: "goal", team: "away", player: "Mikautadze" },
      { minute: 84, type: "goal", team: "away", player: "Cherki" },
    ],
    odds: books(2.2, 3.35, 3.25),
  }),
  match({
    id: "city-palace",
    kickoff: "2026-08-30T13:00:00Z",
    league: LEAGUES.pl,
    home: TEAMS.palace,
    away: TEAMS.city,
    venue: "Selhurst Park",
    events: [
      { minute: 8, type: "goal", team: "away", player: "Haaland" },
      { minute: 22, type: "goal", team: "home", player: "Mateta" },
      { minute: 51, type: "goal", team: "away", player: "Foden" },
      { minute: 63, type: "goal", team: "away", player: "Haaland" },
      { minute: 77, type: "goal", team: "away", player: "Doku" },
    ],
    odds: books(8.5, 5.4, 1.33),
  }),
];

function row(
  rank: number,
  team: Team,
  played: number,
  w: number,
  d: number,
  l: number,
  gf: number,
  ga: number,
  form: StandingRow["form"],
): StandingRow {
  return {
    rank,
    team,
    played,
    won: w,
    draw: d,
    lost: l,
    gf,
    ga,
    gd: gf - ga,
    pts: w * 3 + d,
    form,
  };
}

export const STANDINGS: Record<string, StandingRow[]> = {
  pl: [
    row(1, TEAMS.city, 2, 2, 0, 0, 6, 2, ["W", "W"]),
    row(2, TEAMS.hull, 2, 2, 0, 0, 3, 0, ["W", "W"]),
    row(3, TEAMS.chelsea, 2, 2, 0, 0, 7, 5, ["W", "W"]),
    row(4, TEAMS.brentford, 2, 1, 1, 0, 4, 1, ["W", "D"]),
    row(5, TEAMS.newcastle, 2, 1, 1, 0, 4, 2, ["D", "W"]),
    row(6, TEAMS.everton, 2, 1, 1, 0, 3, 1, ["W", "D"]),
    row(7, TEAMS.leeds, 2, 1, 1, 0, 2, 1, ["W", "D"]),
    row(8, TEAMS.brighton, 2, 1, 0, 1, 7, 4, ["W", "L"]),
    row(9, TEAMS.arsenal, 1, 1, 0, 0, 3, 0, ["W"]),
    row(10, TEAMS.united, 2, 1, 0, 1, 5, 4, ["L", "W"]),
    row(11, TEAMS.sunderland, 2, 1, 0, 1, 2, 2, ["L", "W"]),
    row(12, TEAMS.ipswich, 2, 1, 0, 1, 4, 6, ["W", "L"]),
    row(13, TEAMS.liverpool, 2, 0, 2, 0, 4, 4, ["D", "D"]),
    row(14, TEAMS.bournemouth, 2, 0, 1, 1, 2, 3, ["L", "D"]),
    row(15, TEAMS.forest, 2, 0, 1, 1, 2, 3, ["L", "D"]),
    row(16, TEAMS.fulham, 2, 0, 0, 2, 2, 4, ["L", "L"]),
    row(17, TEAMS.villa, 1, 0, 0, 1, 0, 4, ["L"]),
    row(18, TEAMS.coventry, 2, 0, 0, 2, 0, 4, ["L", "L"]),
    row(19, TEAMS.palace, 2, 0, 0, 2, 1, 6, ["L", "L"]),
    row(20, TEAMS.spurs, 2, 0, 0, 2, 0, 5, ["L", "L"]),
  ],
  ligue1: [
    row(1, TEAMS.monaco, 2, 2, 0, 0, 5, 2, ["W", "W"]),
    row(2, TEAMS.pfc, 2, 1, 1, 0, 5, 2, ["D", "W"]),
    row(3, TEAMS.lille, 2, 1, 1, 0, 4, 2, ["W", "D"]),
    row(4, TEAMS.lyon, 2, 1, 1, 0, 4, 2, ["D", "W"]),
    row(5, TEAMS.rennes, 2, 1, 1, 0, 3, 2, ["W", "D"]),
    row(6, TEAMS.troyes, 2, 1, 1, 0, 3, 2, ["D", "W"]),
    row(7, TEAMS.lens, 2, 1, 0, 1, 4, 2, ["W", "L"]),
    row(8, TEAMS.om, 2, 1, 0, 1, 4, 2, ["L", "W"]),
    row(9, TEAMS.angers, 2, 1, 0, 1, 2, 2, ["W", "L"]),
    row(10, TEAMS.strasbourg, 2, 1, 0, 1, 3, 6, ["W", "L"]),
    row(11, TEAMS.brest, 2, 0, 2, 0, 2, 2, ["D", "D"]),
    row(12, TEAMS.psg, 2, 0, 2, 0, 2, 2, ["D", "D"]),
    row(13, TEAMS.lemans, 2, 0, 1, 1, 1, 2, ["D", "L"]),
    row(14, TEAMS.lorient, 2, 0, 1, 1, 2, 3, ["D", "L"]),
    row(15, TEAMS.hac, 2, 0, 1, 1, 1, 2, ["L", "D"]),
    row(16, TEAMS.toulouse, 2, 0, 1, 1, 1, 3, ["L", "D"]),
    row(17, TEAMS.nice, 2, 0, 1, 1, 1, 4, ["D", "L"]),
    row(18, TEAMS.auxerre, 2, 0, 0, 2, 1, 6, ["L", "L"]),
  ],
  laliga: [
    row(1, TEAMS.barca, 2, 2, 0, 0, 6, 1, ["W", "W"]),
    row(2, TEAMS.madrid, 2, 2, 0, 0, 5, 1, ["W", "W"]),
    row(3, TEAMS.betis, 2, 1, 1, 0, 3, 2, ["W", "D"]),
    row(4, TEAMS.rayo, 2, 1, 0, 1, 3, 3, ["W", "L"]),
    row(5, TEAMS.osasuna, 2, 1, 0, 1, 2, 2, ["L", "W"]),
    row(6, TEAMS.getafe, 2, 0, 1, 1, 1, 2, ["D", "L"]),
  ],
  seriea: [
    row(1, TEAMS.atalanta, 2, 2, 0, 0, 5, 1, ["W", "W"]),
    row(2, TEAMS.roma, 2, 1, 1, 0, 3, 2, ["D", "W"]),
    row(3, TEAMS.bologna, 2, 1, 0, 1, 3, 3, ["W", "L"]),
    row(4, TEAMS.lecce, 2, 0, 1, 1, 2, 3, ["D", "L"]),
  ],
};

function xi(
  rows: Array<[string, number, LineupPlayer["pos"], number, number]>,
): LineupPlayer[] {
  return rows.map(([name, number, pos, x, y]) => ({ name, number, pos, x, y }));
}

export const DETAILS: Record<string, Partial<MatchDetail>> = {
  "villa-arsenal": {
    form: { home: ["L", "W", "D", "W", "L"], away: ["W", "W", "W", "D", "W"] },
    h2h: [
      { date: "2026-04", home: "Arsenal", away: "Aston Villa", score: "2-1" },
      { date: "2025-12", home: "Aston Villa", away: "Arsenal", score: "0-2" },
      { date: "2025-04", home: "Arsenal", away: "Aston Villa", score: "2-2" },
    ],
    stats: [
      { label: "Possession", home: 42, away: 58 },
      { label: "Tirs", home: 9, away: 14 },
      { label: "Tirs cadrés", home: 3, away: 6 },
      { label: "xG", home: 0.9, away: 1.7 },
      { label: "Corners", home: 3, away: 7 },
      { label: "Fautes", home: 12, away: 9 },
      { label: "Passes", home: 381, away: 544 },
    ],
    lineups: {
      home: {
        formation: "4-2-3-1",
        start: xi([
          ["Martínez", 23, "G", 50, 92],
          ["Cash", 2, "D", 82, 72],
          ["Konsa", 4, "D", 64, 78],
          ["Torres", 14, "D", 36, 78],
          ["Digne", 12, "D", 18, 72],
          ["Kamara", 44, "M", 62, 58],
          ["Tielemans", 8, "M", 38, 58],
          ["McGinn", 7, "M", 78, 42],
          ["Rogers", 27, "M", 50, 40],
          ["Bailey", 31, "M", 22, 42],
          ["Watkins", 11, "F", 50, 18],
        ]),
        bench: ["Olsen", "Nedeljkovic", "Maatsen", "Barkley", "Buendía"],
      },
      away: {
        formation: "4-3-3",
        start: xi([
          ["Raya", 22, "G", 50, 92],
          ["Timber", 12, "D", 82, 72],
          ["Saliba", 2, "D", 64, 78],
          ["Gabriel", 6, "D", 36, 78],
          ["Lewis-Skelly", 49, "D", 18, 72],
          ["Rice", 41, "M", 50, 58],
          ["Ødegaard", 8, "M", 68, 46],
          ["Zubimendi", 36, "M", 32, 46],
          ["Saka", 7, "F", 82, 22],
          ["Gyökeres", 14, "F", 50, 16],
          ["Martinelli", 11, "F", 18, 22],
        ]),
        bench: ["Kepa", "White", "Calafiori", "Havertz", "Trossard", "Nwaneri"],
      },
    },
  },
  "barca-rayo": {
    form: { home: ["W", "W", "W", "D", "W"], away: ["W", "L", "W", "D", "L"] },
    stats: [
      { label: "Possession", home: 71, away: 29 },
      { label: "Tirs", home: 18, away: 6 },
      { label: "Tirs cadrés", home: 8, away: 2 },
      { label: "xG", home: 2.4, away: 0.6 },
      { label: "Corners", home: 9, away: 2 },
    ],
    lineups: {
      home: {
        formation: "4-3-3",
        start: xi([
          ["Szczęsny", 25, "G", 50, 92],
          ["Koundé", 23, "D", 82, 72],
          ["Cubarsí", 5, "D", 64, 78],
          ["Martínez", 4, "D", 36, 78],
          ["Balde", 3, "D", 18, 72],
          ["Pedri", 8, "M", 50, 56],
          ["de Jong", 21, "M", 68, 48],
          ["Gavi", 6, "M", 32, 48],
          ["Yamal", 19, "F", 82, 22],
          ["Lewandowski", 9, "F", 50, 16],
          ["Raphinha", 11, "F", 18, 22],
        ]),
        bench: ["Peña", "Araujo", "Fermín", "Ferran", "Olmo"],
      },
      away: {
        formation: "4-4-2",
        start: xi([
          ["Batalla", 1, "G", 50, 92],
          ["Ratiu", 2, "D", 82, 72],
          ["Mumin", 5, "D", 64, 78],
          ["Lejeune", 4, "D", 36, 78],
          ["Chavarría", 3, "D", 18, 72],
          ["Ciss", 6, "M", 78, 50],
          ["Pathé Ciss", 8, "M", 58, 56],
          ["García", 17, "M", 42, 56],
          ["de Frutos", 19, "M", 22, 50],
          ["Palazón", 7, "F", 62, 22],
          ["Embarba", 11, "F", 38, 22],
        ]),
        bench: ["Dimitrievski", "Nteka", "Unbar"],
      },
    },
  },
  "lecce-roma": {
    form: { home: ["D", "L", "D", "W", "L"], away: ["W", "D", "W", "W", "D"] },
    stats: [
      { label: "Possession", home: 38, away: 62 },
      { label: "Tirs", home: 8, away: 16 },
      { label: "xG", home: 0.8, away: 1.9 },
    ],
  },
};

export const HIGHLIGHTS: Highlight[] = [
  {
    id: "h1",
    title: "Villa Park sous les projecteurs",
    matchId: "villa-arsenal",
    league: "Premier League",
    date: "2026-08-31",
    duration: "2:14",
    thumb: "/hero-villa.jpg",
    home: "Aston Villa",
    away: "Arsenal",
  },
  {
    id: "h2",
    title: "Yamal ouvre le score au Camp Nou",
    matchId: "barca-rayo",
    league: "La Liga",
    date: "2026-08-31",
    duration: "1:48",
    thumb: "/hero-camp-nou.jpg",
    home: "Barcelona",
    away: "Rayo Vallecano",
  },
  {
    id: "h3",
    title: "Old Trafford s'enflamme — 5-2",
    matchId: "manu-ipswich",
    league: "Premier League",
    date: "2026-08-30",
    duration: "3:02",
    thumb: "/og.jpg",
    home: "Manchester United",
    away: "Ipswich Town",
  },
  {
    id: "h4",
    title: "Dembélé égalise, le Parc respire",
    matchId: "psg-brest",
    league: "Ligue 1",
    date: "2026-08-30",
    duration: "1:21",
    thumb: "/hero-villa.jpg",
    home: "Paris Saint-Germain",
    away: "Brest",
  },
  {
    id: "h5",
    title: "Palmer, encore, à Stamford Bridge",
    matchId: "chelsea-brighton",
    league: "Premier League",
    date: "2026-08-30",
    duration: "2:36",
    thumb: "/hero-camp-nou.jpg",
    home: "Chelsea",
    away: "Brighton",
  },
  {
    id: "h6",
    title: "Isak transperce Tottenham",
    matchId: "spurs-newcastle",
    league: "Premier League",
    date: "2026-08-29",
    duration: "1:55",
    thumb: "/og.jpg",
    home: "Tottenham Hotspur",
    away: "Newcastle United",
  },
];
